### PR TITLE
Updates to gen-users-and-security-levels

### PR DESCRIPTION
**Pull request by cornelisonc**
Fixed: The generated users table did not have a FK reference to the Security Levels table.

Added: Command now accepts args to automatically generate an admin user with provided name, email, and password, preventing the need for an extra deploy file just to add one.

### CODE REVIEW

**Comment by griffbrad** [comment]
If the admin user arguments are optional, what happens when I skip them? Won't the generated SQL file error out -- or at least produce a non-sensical, non-functional admin user?

**Comment by cornelisonc** [comment]
[If no admin user arguments are provided, the command will work the same as it does now -- it will just generate the Users table without the Admin user (using `*-create-users.sql`).](https://github.com/cornelisonc/dewdrop/blob/802d5d702e25722bc9a47858f9b42393b4f112a6/Dewdrop/Cli/Command/GenUsersAndSecurityLevels.php#L188)

[If some admin user arguments are provided, but not all 3, the command will throw an error with a message saying that all admin user args must be provided if you are trying to generate an admin user.
](https://github.com/cornelisonc/dewdrop/blob/802d5d702e25722bc9a47858f9b42393b4f112a6/Dewdrop/Cli/Command/GenUsersAndSecurityLevels.php#L149)

[If all 3 admin user args are provided, the `*-create-users-with-admin-user.sql` template is called instead of the `*-create-users.sql` template, as well as passing the admin user args to it.](https://github.com/cornelisonc/dewdrop/blob/802d5d702e25722bc9a47858f9b42393b4f112a6/Dewdrop/Cli/Command/GenUsersAndSecurityLevels.php#L180)

**Comment by griffbrad** [comment]
I see.  Can we modify it so that it doesn't duplicate the CREATE TABLE users; statement across the original template and the with-user template?

**Comment by cornelisonc** [comment]
How does this 👆🏼look @griffbrad ?

**Comment by griffbrad** [comment]
Merged!

**Pull request merged**
